---
# Setup LVM partition

- name: display vars values (lvm_vgname)
  debug:
     msg: "default: {{ lvm_vgname }}"

- name: display vars values (lvm_lvmount)
  debug:
     msg: "default:  {{ lvm_lvmount }}"

- name: display vars values (lvm_lvsize)
  debug:
     msg: "default:{{ lvm_lvsize}}"

- name: display vars values (lvm_lvfilesystem)
  debug:
     msg: "default:  {{ lvm_lvfilesystem }}"

- name: System | install lvm2
  become: true
  ansible.builtin.dnf:
    update_cache: true
    name:
      - lvm2
    state: present

- name: System | install lvm2
  become: true
  command: vgs --help
  register: output

- name: display output  (output)
  debug:
     msg: "default:  {{ output }}"

- name: storage | Create a volume group on top of /dev
  become: yes
  community.general.lvg:
    vg: "{{ lvm_vgname }}"
    pvs: /dev

- name: storage | create logical volume
  become: true
  lvol:
    vg: "{{ lvm_vgname }}"
    lv: "{{ lvm_lvname }}"
    size: "{{ lvm_lvsize }}"
    shrink: "{{ lvm_shrink | default(True) }}"
    opts: "{{ lvm_lvopts | default(None) }}"

- name: storage | filesystem
  become: true
  filesystem:
    fstype: "{{ lvm_lvfilesystem }}"
    dev: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    resizefs: true


- name: storage | mount
  become: true
  mount:
    name: "{{ lvm_lvmount }}"
    src: /dev/{{ lvm_vgname }}/{{ lvm_lvname }}
    dump: "1"
    passno: "2"
    fstype: "{{ lvm_lvfilesystem }}"
    state: mounted
